/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Jagger.h
 #	source generated by 4D Plugin Wizard
 #	Project : Jagger
 #	author : miyako
 #	2025/04/21
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_JAGGER_H
#define PLUGIN_JAGGER_H

#include "4DPluginAPI.h"
#if VERSIONMAC
#import <Cocoa/Cocoa.h>
#else
#include <Shlobj.h>
#include <chrono>
#endif

#include "jagger.h"
#include <sstream>
#include <iostream>

#include "C_TEXT.h"

#pragma mark -

static void Jagger_split(PA_PluginParameters params);
static void Jagger_tokenize(PA_PluginParameters params);
static void Jagger_train(PA_PluginParameters params);
static void Jagger_set_model(PA_PluginParameters params);
static void Jagger_get_model(PA_PluginParameters params);

#endif /* PLUGIN_JAGGER_H */
